### ISSUE TITLE
Pressing 9 wont fill your invintory and pressing 8/f11 wont give you chicken coop upgrades and ogdens extra food upgrades

### ISSUE THREAD

**Issue by DogeisCut** [UnityPluginManager/SlimeRancher.DebugMenu#2] opened 2018-08-20 01:03 UTC
title says it all

**Comment by JustaGoat** [comment] 2018-08-20 20:48
this is what my post is about. i wish it worked

**Comment by DaZombieKiller** [comment] 2018-08-20 22:36
Yeah, I'm gonna close this as it is a duplicate of issue #1

I have plans to fix it ASAP, I just haven't had the time lately (plus I recently got sick, so that's put a bit of a dampener on things too)

**Closed as completed by DaZombieKiller** 2018-08-20 22:36 UTC
